---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# heidel

<!-- badges: start -->
<!-- badges: end -->

This packages is just some random functions that are used for very specific tasks during my study. It is only to share with collaborators and between workstations.

## Installation
Install package using devtools
``` r
if(!require("devtools")) install.packages("devtools")
library(devtools)
devtools::install_github("SorenHeidelbach/heidel")
```
# Usage examples
## count_unique

```{r count_unique, warning = F}
library(heidel)

counted = count_unique(iris, 
                       subset_by = "Species", 
                       count_col = 1)
head(counted)
species <- iris$Species[c(1,60)]
counted = count_unique(iris, 
                       subset_by = "Species", 
                       count_col = "Sepal.Length",
                       subset_values = species)
head(counted)
```

## tax_lineage_from_accesion
```{r tax_lineage_from_accesion, warning = F}
tax_lineage_from_accesion(accession = c("NZ_CP027599.1", "NR_042763"))

tax_lineage_from_accesion(accession = c("NZ_CP027599.1", "7"),
                          custom_tax = c("clade", "genus", "species"))
```

## evaluate_contig_coverage
```{r evaluate_contig_coverage, warning = F}
# Some large contigs have been removed from depth file to reduce file size.
evaluate_contig_coverage(path = "depth.AF1_seqtk.filt.txt", 
                         parametric = T) 

evaluate_contig_coverage(path = "depth.AF1_seqtk.filt.txt", 
                         parametric = F) 
```

